/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppartementsRouteImport } from './routes/appartements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminLeadsRouteImport } from './routes/_admin.admin.leads'
import { Route as AdminAdminPagesIndexRouteImport } from './routes/_admin.admin.pages.index'
import { Route as AdminAdminPagesNewRouteImport } from './routes/_admin.admin.pages.new'
import { Route as AdminAdminPagesIdRouteImport } from './routes/_admin.admin.pages.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppartementsRoute = AppartementsRouteImport.update({
  id: '/appartements',
  path: '/appartements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminLeadsRoute = AdminAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPagesIndexRoute = AdminAdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPagesNewRoute = AdminAdminPagesNewRouteImport.update({
  id: '/pages/new',
  path: '/pages/new',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPagesIdRoute = AdminAdminPagesIdRouteImport.update({
  id: '/pages/$id',
  path: '/pages/$id',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/appartements': typeof AppartementsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/leads': typeof AdminAdminLeadsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/pages/$id': typeof AdminAdminPagesIdRoute
  '/admin/pages/new': typeof AdminAdminPagesNewRoute
  '/admin/pages/': typeof AdminAdminPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/appartements': typeof AppartementsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/leads': typeof AdminAdminLeadsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/pages/$id': typeof AdminAdminPagesIdRoute
  '/admin/pages/new': typeof AdminAdminPagesNewRoute
  '/admin/pages': typeof AdminAdminPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/appartements': typeof AppartementsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/_admin/admin/leads': typeof AdminAdminLeadsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/pages/$id': typeof AdminAdminPagesIdRoute
  '/_admin/admin/pages/new': typeof AdminAdminPagesNewRoute
  '/_admin/admin/pages/': typeof AdminAdminPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/appartements'
    | '/sitemap.xml'
    | '/admin'
    | '/admin/login'
    | '/admin/leads'
    | '/admin/settings'
    | '/admin/'
    | '/admin/pages/$id'
    | '/admin/pages/new'
    | '/admin/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/appartements'
    | '/sitemap.xml'
    | '/admin/login'
    | '/admin/leads'
    | '/admin/settings'
    | '/admin'
    | '/admin/pages/$id'
    | '/admin/pages/new'
    | '/admin/pages'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_admin'
    | '/about'
    | '/appartements'
    | '/sitemap.xml'
    | '/_admin/admin'
    | '/admin/login'
    | '/_admin/admin/leads'
    | '/_admin/admin/settings'
    | '/_admin/admin/'
    | '/_admin/admin/pages/$id'
    | '/_admin/admin/pages/new'
    | '/_admin/admin/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  AppartementsRoute: typeof AppartementsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appartements': {
      id: '/appartements'
      path: '/appartements'
      fullPath: '/appartements'
      preLoaderRoute: typeof AppartementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/leads': {
      id: '/_admin/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminAdminLeadsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/pages/': {
      id: '/_admin/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminAdminPagesIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/pages/new': {
      id: '/_admin/admin/pages/new'
      path: '/pages/new'
      fullPath: '/admin/pages/new'
      preLoaderRoute: typeof AdminAdminPagesNewRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/pages/$id': {
      id: '/_admin/admin/pages/$id'
      path: '/pages/$id'
      fullPath: '/admin/pages/$id'
      preLoaderRoute: typeof AdminAdminPagesIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminLeadsRoute: typeof AdminAdminLeadsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminPagesIdRoute: typeof AdminAdminPagesIdRoute
  AdminAdminPagesNewRoute: typeof AdminAdminPagesNewRoute
  AdminAdminPagesIndexRoute: typeof AdminAdminPagesIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminLeadsRoute: AdminAdminLeadsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminPagesIdRoute: AdminAdminPagesIdRoute,
  AdminAdminPagesNewRoute: AdminAdminPagesNewRoute,
  AdminAdminPagesIndexRoute: AdminAdminPagesIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  AppartementsRoute: AppartementsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
